import os

from reportlab.lib import colors

from reportlab.lib.enums import TA_CENTER

from reportlab.lib.pagesizes import (
    A4,
    LETTER,
    landscape,
    portrait
)

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from reportlab.lib.units import mm

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


# ----------------------------------------
# Get Page Size
# ----------------------------------------

def get_page_size(design=None):

    if design is None:
        design = {}

    page_size = design.get(
        "page_size",
        "A4"
    )

    orientation = design.get(
        "orientation",
        "portrait"
    )

    # Page size
    if page_size == "LETTER":

        page = LETTER

    else:

        page = A4

    # Orientation
    if orientation == "landscape":

        page = landscape(page)

    else:

        page = portrait(page)

    return page


# ----------------------------------------
# Generate Student PDF
# ----------------------------------------

def generate_student_pdf(
    student_result,
    profile,
    output_path
):
    """
    Generate PDF result for one student.

    Uses the reusable profile for:
    - College Name
    - Page size
    - Orientation
    - Header
    - Footer
    - Profile information
    """

    # --------------------------------
    # Get Design Settings
    # --------------------------------

    design = profile.get(
        "design",
        {}
    )

    page_size = get_page_size(
        design
    )

    header_title = design.get(
        "header_title",
        "STUDENT RESULT"
    )

    header_subtitle = design.get(
        "header_subtitle",
        ""
    )

    footer_text = design.get(
        "footer_text",
        "Generated by Resultra"
    )

    # --------------------------------
    # Create PDF Document
    # --------------------------------

    document = SimpleDocTemplate(

        output_path,

        pagesize=page_size,

        rightMargin=15 * mm,

        leftMargin=15 * mm,

        topMargin=15 * mm,

        bottomMargin=15 * mm

    )

    # --------------------------------
    # Styles
    # --------------------------------

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(

        "ResultTitle",

        parent=styles["Title"],

        alignment=TA_CENTER,

        fontSize=18,

        spaceAfter=8

    )

    subtitle_style = ParagraphStyle(

        "ResultSubtitle",

        parent=styles["Normal"],

        alignment=TA_CENTER,

        fontSize=11,

        spaceAfter=5

    )

    center_style = ParagraphStyle(

        "Center",

        parent=styles["Normal"],

        alignment=TA_CENTER,

        fontSize=10

    )

    footer_style = ParagraphStyle(

        "Footer",

        parent=styles["Normal"],

        alignment=TA_CENTER,

        fontSize=8

    )

    story = []

    # ========================================
    # HEADER
    # ========================================

    college_name = profile.get(
        "college_name",
        ""
    )

    if college_name:

        story.append(
            Paragraph(
                college_name,
                title_style
            )
        )

    if header_title:

        story.append(
            Paragraph(
                header_title,
                subtitle_style
            )
        )

    if header_subtitle:

        story.append(
            Paragraph(
                header_subtitle,
                subtitle_style
            )
        )

    # ========================================
    # PROFILE INFORMATION
    # ========================================

    department = profile.get(
        "department",
        ""
    )

    course = profile.get(
        "course",
        ""
    )

    class_name = profile.get(
        "class",
        ""
    )

    semester = profile.get(
        "semester",
        ""
    )

    academic_year = profile.get(
        "academic_year",
        ""
    )

    examination = profile.get(
        "examination",
        ""
    )

    if department:

        story.append(
            Paragraph(
                f"<b>Department:</b> "
                f"{department}",
                center_style
            )
        )

    if course:

        story.append(
            Paragraph(
                f"<b>Course:</b> "
                f"{course}",
                center_style
            )
        )

    if class_name:

        story.append(
            Paragraph(
                f"<b>Class:</b> "
                f"{class_name}",
                center_style
            )
        )

    if semester:

        story.append(
            Paragraph(
                f"<b>Semester:</b> "
                f"{semester}",
                center_style
            )
        )

    if academic_year:

        story.append(
            Paragraph(
                f"<b>Academic Year:</b> "
                f"{academic_year}",
                center_style
            )
        )

    if examination:

        story.append(
            Paragraph(
                f"<b>Examination:</b> "
                f"{examination}",
                center_style
            )
        )

    story.append(
        Spacer(1, 12)
    )

    # ========================================
    # STUDENT INFORMATION
    # ========================================

    student_info = [

        [
            "Student Name",
            str(
                student_result.get(
                    "Student Name",
                    ""
                )
            )
        ],

        [
            "Roll No",
            str(
                student_result.get(
                    "Roll No",
                    ""
                )
            )
        ]

    ]

    student_table = Table(

        student_info,

        colWidths=[
            45 * mm,
            110 * mm
        ]

    )

    student_table.setStyle(

        TableStyle([

            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.black
            ),

            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.lightgrey
            ),

            (
                "FONTNAME",
                (0, 0),
                (0, -1),
                "Helvetica-Bold"
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),

            (
                "PADDING",
                (0, 0),
                (-1, -1),
                6
            )

        ])

    )

    story.append(
        student_table
    )

    story.append(
        Spacer(1, 12)
    )

    # ========================================
    # SUBJECT RESULT TABLE
    # ========================================

    subject_table_data = [

        [
            "Subject",
            "Marks",
            "Grade",
            "Grade Point",
            "Credit",
            "Credit Point",
            "Status"
        ]

    ]

    subjects = student_result.get(
        "subjects",
        {}
    )

    for subject, data in subjects.items():

        subject_table_data.append(

            [

                str(subject),

                str(
                    data.get(
                        "marks",
                        ""
                    )
                ),

                str(
                    data.get(
                        "grade",
                        ""
                    )
                ),

                str(
                    data.get(
                        "grade_point",
                        ""
                    )
                ),

                str(
                    data.get(
                        "credit",
                        ""
                    )
                ),

                str(
                    data.get(
                        "credit_point",
                        ""
                    )
                ),

                str(
                    data.get(
                        "status",
                        ""
                    )
                )

            ]

        )

    subject_table = Table(

        subject_table_data,

        repeatRows=1

    )

    subject_table.setStyle(

        TableStyle([

            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.black
            ),

            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.lightgrey
            ),

            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold"
            ),

            (
                "ALIGN",
                (1, 1),
                (-1, -1),
                "CENTER"
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),

            (
                "PADDING",
                (0, 0),
                (-1, -1),
                5
            )

        ])

    )

    story.append(
        subject_table
    )

    story.append(
        Spacer(1, 12)
    )

    # ========================================
    # RESULT SUMMARY
    # ========================================

    summary_data = [

        [
            "Total Marks",

            (
                f"{student_result.get('total', 0)} / "
                f"{student_result.get('maximum_marks', 0)}"
            )

        ],

        [
            "Percentage",

            (
                f"{student_result.get('percentage', 0)}%"
            )

        ],

        [
            "Total Credits",

            str(
                student_result.get(
                    "total_credits",
                    0
                )
            )

        ],

        [
            "Total Credit Points",

            str(
                student_result.get(
                    "total_credit_points",
                    0
                )
            )

        ],

        [
            "SGPA",

            str(
                student_result.get(
                    "sgpa",
                    0
                )
            )

        ],

        [
            "CGPA",

            str(
                student_result.get(
                    "cgpa",
                    0
                )
            )

        ],

        [
            "Overall Result",

            str(
                student_result.get(
                    "result",
                    ""
                )
            )

        ]

    ]

    summary_table = Table(

        summary_data,

        colWidths=[
            60 * mm,
            70 * mm
        ]

    )

    summary_table.setStyle(

        TableStyle([

            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.black
            ),

            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.lightgrey
            ),

            (
                "FONTNAME",
                (0, 0),
                (0, -1),
                "Helvetica-Bold"
            ),

            (
                "FONTNAME",
                (0, 4),
                (-1, 6),
                "Helvetica-Bold"
            ),

            (
                "ALIGN",
                (1, 0),
                (1, -1),
                "CENTER"
            ),

            (
                "PADDING",
                (0, 0),
                (-1, -1),
                6
            )

        ])

    )

    story.append(
        summary_table
    )

    story.append(
        Spacer(1, 20)
    )

    # ========================================
    # FOOTER
    # ========================================

    if footer_text:

        story.append(
            Paragraph(
                footer_text,
                footer_style
            )
        )

    # ========================================
    # BUILD PDF
    # ========================================

    document.build(
        story
    )

    return output_path