from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


def generate_student_pdf(student_result, profile, output_path):
    """
    Generate a result PDF for one student.
    """

    document = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ResultTitle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=18,
        spaceAfter=10
    )

    center_style = ParagraphStyle(
        "CenterText",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=11
    )

    story = []

    # College / Department information
    story.append(
        Paragraph(
            profile.get("department", ""),
            title_style
        )
    )

    story.append(
        Paragraph(
            profile.get("course", ""),
            center_style
        )
    )

    story.append(Spacer(1, 8))

    # Examination information
    story.append(
        Paragraph(
            profile.get("examination", ""),
            center_style
        )
    )

    story.append(Spacer(1, 20))

    # Student information
    student_info = [
        ["Roll No", str(student_result["Roll No"])],
        ["Student Name", str(student_result["Student Name"])],
        ["Class", profile.get("class", "")],
        ["Semester", profile.get("semester", "")],
        ["Academic Year", profile.get("academic_year", "")]
    ]

    student_table = Table(
        student_info,
        colWidths=[130, 330]
    )

    student_table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("PADDING", (0, 0), (-1, -1), 7),
        ])
    )

    story.append(student_table)

    story.append(Spacer(1, 20))

    # Subject marks table
    marks_data = [
        ["Subject", "Marks", "Grade", "Status"]
    ]

    for subject, result in student_result["subjects"].items():

        marks_data.append([
            subject,
            str(result["marks"]),
            result["grade"],
            result["status"]
        ])

    marks_table = Table(
        marks_data,
        colWidths=[220, 80, 80, 80]
    )

    marks_table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ALIGN", (1, 1), (-1, -1), "CENTER"),
            ("PADDING", (0, 0), (-1, -1), 7),
        ])
    )

    story.append(marks_table)

    story.append(Spacer(1, 20))

    # Final result
    summary_data = [
        ["Total Marks", str(student_result["total"])],
        ["Maximum Marks", str(student_result["maximum_marks"])],
        ["Percentage", f'{student_result["percentage"]}%'],
        ["Result", student_result["result"]]
    ]

    summary_table = Table(
        summary_data,
        colWidths=[160, 120]
    )

    summary_table.setStyle(
        TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("PADDING", (0, 0), (-1, -1), 7),
        ])
    )

    story.append(summary_table)

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            "Generated by Resultra",
            center_style
        )
    )

    document.build(story)