import os

from reportlab.lib import colors

from reportlab.lib.enums import TA_CENTER

from reportlab.lib.pagesizes import (
    A4,
    LETTER,
    landscape,
    portrait
)

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from reportlab.lib.units import mm

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    HRFlowable
)


# ----------------------------------------
# Get Page Size
# ----------------------------------------

def get_page_size(design=None):

    if design is None:
        design = {}

    page_size = design.get(
        "page_size",
        "A4"
    )

    orientation = design.get(
        "orientation",
        "portrait"
    )

    # Page size
    if page_size == "LETTER":

        page = LETTER

    else:

        page = A4

    # Orientation
    if orientation == "landscape":

        page = landscape(page)

    else:

        page = portrait(page)

    return page


# ----------------------------------------
# Generate Student PDF
# ----------------------------------------

def generate_student_pdf(
    student_result,
    profile,
    output_path
):
    """
    Generate PDF result for one student.

    Uses the reusable profile for:
    - College Name
    - Page size
    - Orientation
    - Header
    - Footer
    - Profile information
    """

    # --------------------------------
    # Get Design Settings
    # --------------------------------

    design = profile.get(
        "design",
        {}
    )

    page_size = get_page_size(
        design
    )

    header_title = design.get(
        "header_title",
        "STUDENT RESULT"
    )

    header_subtitle = design.get(
        "header_subtitle",
        ""
    )

    footer_text = design.get(
        "footer_text",
        "Generated by Resultra"
    )

    # --------------------------------
    # Create PDF Document
    # --------------------------------

    document = SimpleDocTemplate(

        output_path,

        pagesize=page_size,

        rightMargin=15 * mm,

        leftMargin=15 * mm,

        topMargin=15 * mm,

        bottomMargin=15 * mm

    )

    # --------------------------------
    # Styles
    # --------------------------------

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ResultTitle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=18,
        leading=22,
        spaceAfter=6
    )

    college_style = ParagraphStyle(
        "CollegeName",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=20,
        leading=24,
        spaceAfter=4
    )

    subtitle_style = ParagraphStyle(
        "ResultSubtitle",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=11,
        leading=14,
        spaceAfter=5
    )

    center_style = ParagraphStyle(
        "Center",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=10
    )

    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=8
    )

    story = []

    # ========================================
    # HEADER
    # ========================================

    college_name = profile.get(
        "college_name",
        ""
    )

    if college_name:

        story.append(
            Paragraph(
                college_name,
                college_style
            )
        )

    if header_title:

        story.append(
            Paragraph(
                header_title,
                subtitle_style
            )
        )

    if header_subtitle:

        story.append(
            Paragraph(
                header_subtitle,
                subtitle_style
            )
        )

    # Header separator

    story.append(
        Spacer(1, 4)
    )

    story.append(
        HRFlowable(
            width="100%",
            thickness=1,
            spaceBefore=2,
            spaceAfter=8
        )
    )

    # ========================================
    # PROFILE INFORMATION
    # ========================================

    department = profile.get(
        "department",
        ""
    )

    course = profile.get(
        "course",
        ""
    )

    class_name = profile.get(
        "class",
        ""
    )

    semester = profile.get(
        "semester",
        ""
    )

    academic_year = profile.get(
        "academic_year",
        ""
    )

    examination = profile.get(
        "examination",
        ""
    )

    profile_info = [
        [
            "Department",
            department,
            "Course",
            course
        ],
        [
            "Class",
            class_name,
            "Semester",
            semester
        ],
        [
            "Academic Year",
            academic_year,
            "Examination",
            examination
        ]
    ]

    profile_table = Table(
        profile_info,
        colWidths=[
            30 * mm,
            45 * mm,
            30 * mm,
            45 * mm
        ]
    )

    profile_table.setStyle(
        TableStyle([
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.black
            ),

            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.lightgrey
            ),

            (
                "BACKGROUND",
                (2, 0),
                (2, -1),
                colors.lightgrey
            ),

            (
                "FONTNAME",
                (0, 0),
                (0, -1),
                "Helvetica-Bold"
            ),

            (
                "FONTNAME",
                (2, 0),
                (2, -1),
                "Helvetica-Bold"
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),

            (
                "PADDING",
                (0, 0),
                (-1, -1),
                6
            )
        ])
    )

    story.append(
        profile_table
    )

    story.append(
        Spacer(1, 12)
    )

    # ========================================
    # STUDENT INFORMATION
    # ========================================

    student_info = [
        [
            "Student Name",
            str(
                student_result.get(
                    "Student Name",
                    ""
                )
            )
        ],
        [
            "Roll No",
            str(
                student_result.get(
                    "Roll No",
                    ""
                )
            )
        ]
    ]

    student_table = Table(
        student_info,
        colWidths=[
            35 * mm,
            115 * mm
        ]
    )

    student_table.setStyle(
        TableStyle([
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.black
            ),

            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.lightgrey
            ),

            (
                "FONTNAME",
                (0, 0),
                (0, -1),
                "Helvetica-Bold"
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),

            (
                "PADDING",
                (0, 0),
                (-1, -1),
                7
            )
        ])
    )

    story.append(
        student_table
    )

    story.append(
        Spacer(1, 12)
    )

    # ========================================
    # SUBJECT RESULT TABLE
    # ========================================

    subject_table_data = [

        [
            "Subject",
            "Marks",
            "Grade",
            "Grade Point",
            "Credit",
            "Credit Point",
            "Status"
        ]

    ]

    subjects = student_result.get(
        "subjects",
        {}
    )

    for subject, data in subjects.items():

        subject_table_data.append(

            [

                str(subject),

                str(
                    data.get(
                        "marks",
                        ""
                    )
                ),

                str(
                    data.get(
                        "grade",
                        ""
                    )
                ),

                str(
                    data.get(
                        "grade_point",
                        ""
                    )
                ),

                str(
                    data.get(
                        "credit",
                        ""
                    )
                ),

                str(
                    data.get(
                        "credit_point",
                        ""
                    )
                ),

                str(
                    data.get(
                        "status",
                        ""
                    )
                )

            ]

        )

    subject_table = Table(
        subject_table_data,
        colWidths=[
            38 * mm,
            18 * mm,
            18 * mm,
            22 * mm,
            18 * mm,
            20 * mm,
            16 * mm
        ],
        repeatRows=1
    )

    subject_table.setStyle(
        TableStyle([
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.black
            ),

            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.lightgrey
            ),

            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold"
            ),

            (
                "ALIGN",
                (1, 1),
                (-1, -1),
                "CENTER"
            ),

            (
                "ALIGN",
                (0, 0),
                (-1, 0),
                "CENTER"
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),

            (
                "PADDING",
                (0, 0),
                (-1, -1),
                5
            )
        ])
    )

    story.append(
        subject_table
    )

    story.append(
        Spacer(1, 12)
    )

    # ========================================
    # RESULT SUMMARY
    # ========================================

    summary_data = [

        [
            "Total Marks",

            (
                f"{student_result.get('total', 0)} / "
                f"{student_result.get('maximum_marks', 0)}"
            )

        ],

        [
            "Percentage",

            (
                f"{student_result.get('percentage', 0)}%"
            )

        ],

        [
            "Total Credits",

            str(
                student_result.get(
                    "total_credits",
                    0
                )
            )

        ],

        [
            "Total Credit Points",

            str(
                student_result.get(
                    "total_credit_points",
                    0
                )
            )

        ],

        [
            "SGPA",

            str(
                student_result.get(
                    "sgpa",
                    0
                )
            )

        ],

        [
            "CGPA",

            str(
                student_result.get(
                    "cgpa",
                    0
                )
            )

        ],

        [
            "Overall Result",

            str(
                student_result.get(
                    "result",
                    ""
                )
            )

        ]

    ]

    summary_table = Table(
        summary_data,
        colWidths=[
            75 * mm,
            75 * mm
        ]
    )

    summary_table.setStyle(
        TableStyle([
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.black
            ),

            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.lightgrey
            ),

            (
                "FONTNAME",
                (0, 0),
                (0, -1),
                "Helvetica-Bold"
            ),

            (
                "FONTNAME",
                (0, 4),
                (-1, 6),
                "Helvetica-Bold"
            ),

            (
                "ALIGN",
                (1, 0),
                (1, -1),
                "CENTER"
            ),

            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE"
            ),

            (
                "PADDING",
                (0, 0),
                (-1, -1),
                6
            )
        ])
    )

    story.append(
        summary_table
    )

    story.append(
        Spacer(1, 20)
    )

    # ========================================
    # FOOTER
    # ========================================

    if footer_text:

        story.append(
            Spacer(1, 12)
        )

        story.append(
            HRFlowable(
                width="100%",
                thickness=0.5,
                spaceBefore=2,
                spaceAfter=6
            )
        )

        story.append(
            Paragraph(
                footer_text,
                footer_style
            )
        )

    # ========================================
    # BUILD PDF
    # ========================================

    document.build(
        story
    )

    return output_path